title: Codeforces editorials
description: "Codeforces editorials"
author:
  name: "Adam Koprowski"
  email: "Adam.Koprowski@gmail.com"
  url: ""

source: .
destination: ./_site
permalink: /:title
baseurl: /codeforces-editorials

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  problems:
    output: true
    permalink: /p/:path

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-datapage-generator

page_gen:
- data: 'problems'
  template: 'problem'
  index_files: true
  name: 'id'
  title: 'name'
  extension: 'md'


# Custom variables
owner : "Adam Koprowski"
year : "2020"
